import { FileText } from 'lucide-react';

export function FinancialSummaryCard() {
  return (
    <div className="bg-white rounded-lg border border-gray-200 p-8" style={{ boxShadow: 'var(--shadow-md)' }}>
      <div className="flex items-center gap-3 mb-6">
        <div className="w-9 h-9 bg-blue-50 rounded-lg flex items-center justify-center">
          <FileText className="w-4.5 h-4.5 text-blue-600" />
        </div>
        <h2 className="text-[18px] font-semibold tracking-tight text-gray-900">
          Financial Summary
        </h2>
      </div>
      
      <div className="space-y-4 text-[14px] leading-[1.7] text-gray-600">
        <p>
          The company demonstrated strong top-line growth in Q4 2021, with revenue increasing by 15% 
          compared to Q3, reaching 2.4 billion VND. This growth was primarily driven by expanded 
          market penetration and successful product launches.
        </p>
        
        <p>
          However, profitability metrics show concerning trends. The net profit margin declined from 
          12% to 8%, reflecting a 33% drop in absolute net profit to 192 million VND. This compression 
          was largely attributed to a 20% surge in operating expenses, particularly in sales and 
          administrative costs.
        </p>
        
        <div className="pt-4 border-t border-gray-100">
          <p>
            Most notably, cash flow from operations turned negative for the first time in recent quarters, 
            signaling potential liquidity challenges. Management should prioritize expense optimization 
            and working capital efficiency to restore sustainable profitability while maintaining growth 
            momentum.
          </p>
        </div>
      </div>

      <div className="mt-6 pt-6 border-t border-gray-100 flex items-center justify-between">
        <span className="text-[11px] text-gray-500">
          Generated by AI • Last updated 2 hours ago
        </span>
        <button className="text-[12px] text-blue-600 hover:text-blue-700 font-medium transition-colors">
          View Full Report →
        </button>
      </div>
    </div>
  );
}
